### ISSUE TITLE
Missing Values in Example Calculation for Awesome Oscillator

### ISSUE THREAD

**Issue by bennycode** [TulipCharts/tulipindicators#112]
I was reading the [Awesome Oscillator](https://tulipindicators.org/ao) documentation and noticed that the chart shows ao values (between 0 and 1) but the table from the "Example Calculation" doesn't list any return values.

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/128234009-0557fb9a-42c2-422f-b2dd-39c42d39711c.png)

**Comment by codeplea** [comment]
Yeah, this is a website issue. That indicator needs at least 34 bars of input to generate just one output (because of the 34-bar moving average it uses). The issue is that the website only uses a few bars of example data, and it's not enough to do anything here.

If I revamp the documentation, I'll fix this.

**Comment by codeplea** [comment]
The chart is showing inputs only. There is no output on the chart.

untest.txt is an automated regression test. It suffers from the same problem as the website. untest.txt's purpose is to check for unintended changes in indicator output values, and it's far from comprehensive. It is just one line of defense out of many.

In the next update I will look at making untest.txt use more data. I don't really see any downside to that.

There is a unit test for ao in extra.txt, and it does include outputs in that file.

**Comment by bennycode** [comment]
Thank you for pointing me to the `extra.txt` file. This helped me to verify the calculations! 🙂
