### ISSUE TITLE
ta data is incorrect (or maybe design limitation)

### ISSUE THREAD

**Issue by bhan22** [TulipCharts/tulipindicators#14]
I have a set of arrays representing ohlc data which is expanding in real-time market data (I just adding to the array of new coming data), so the memory (actually shared memory) has been allocated already, what I needed to do is just passing the array pointer to tulip indicator to get the ta func (I'm using C++)
(it's actually 2 dimension array, first index is for timeframe , out_ti is also 2 dim array, first idx for different kind of ta)
for(int startIdx....){
    TI_REAL  options[]      = {(double)prd};
    TI_REAL  *inputs[]      = {&data_high[0][startIdx],&data_low[0][startIdx],data_close[0][startIdx]};
    TI_REAL  *outputs[]     = {&out_ti[0][startidx],&out_ti[1][startIdx]};
    ti_di(prd,inputs,options,outputs);
}
since my data array is huge, I use prd as data size instead of actually data size (otherwise it will repeatedly calc), 

the ta data coming out for prd is not same when the whole data size is passing in (which would be really wise for calc again and again, since it is real-time app)

would it be possible to update TA for one output ta slot instead of a set of ta slot???

Thanks
Jeff

**Comment by codeplea** [comment]
Most indicator values are influenced by old data, and often from data much older than the period option. For example, the [exponential moving average](https://tulipindicators.org/ema) output is influenced by all previous input data. So there is no possible way for TI to calculate the correct output if you're not giving it all the input data.

I understand that you want to give it less data because you want it to run faster, but have you actually profiled it and found it to be too slow? Most indicators will [run a hundred million bars per second](https://tulipindicators.org/benchmark). I think you can probably afford to pass in a few hundred bars instead of whatever `prd` is.

**Comment by bhan22** [comment]
thank you so much for you help, yes, it was my misunderstanding, ta with
memory effect turn to be same value, so now i handle it with fixed set of
extra previous data, ti is an awesome tool, i was using ta lib, now using
ti also, it is fast

you did a great job and very nice to share it publicly

thanks again

regards
jeff

**Comment by codeplea** [comment]
I'm glad you're finding it useful!
