### ISSUE TITLE
Allocation responsibility

### ISSUE THREAD

**Issue by rdbuf** [TulipCharts/tulipindicators#49]
Was the caller side made responsible for buffer allocation/deallocation for
- performance reasons?
- cross-language integration concerns?
- philosophical arguments?

For instance, when an indicator requires an internal buffer, should we allocate it inside of the indicator or take it as a function argument? Currently, `grep malloc indicators/*.c` results in 0 occurrences.

**Comment by codeplea** [comment]
All of those are good arguments for why the caller must allocate output space for the indicator results.

However, some algorithms really do need to allocate a temporary buffer. All of the current indicators that allocate temporary buffers do it through the `buffer.h` and `buffer.c` functions. (e.g., ADXR, CCI, CVI, HMA, MASS, MFI, STOCH, STOCHRSI, ULTOSC). `ti_buffer` makes for an efficient circular buffer, which is usually what is needed. It can also keep track of the buffer sum.

If you can use `ti_buffer`, use it. Otherwise, feel free to use `malloc` directly. Also feel free to add a TI_OUT_OF_MEMORY return value (currently it only has TI_OKAY and TI_INVALID_OPTION). I've been meaning to do that for a while.

**Comment by rdbuf** [comment]
OK, thanks for the feedback!
