### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by tux-00** [TulipCharts/tulipindicators#93]
What is the current project status ?
I can see some PR open since some months ago and the code frequency is very low.

**Comment by codeplea** [comment]
This has been an ongoing project since 2010. It's not going anywhere. I will continue to add more features over time. There are no major bugs in the current release, and if there were, I would address them.

Most of the open pull requests are by rdbuf. He is no longer working on the project, unfortunately, and his PRs need work. Mostly they need testing and documentation before being accepted. There are a few other issues that need to be worked through in the 0.9 branch also.

**Comment by codeplea** [comment]
Since rdbuf is no longer active, I think I will accept all of his PRs into 0.9 and then deal with the issues from that point.
